# Generated by Django 3.1 on 2020-08-17 09:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200817_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirm_code',
            field=models.UUIDField(default=uuid.UUID('8d4fa105-be18-43a5-8ef5-3d45e26206f6'), editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='passport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.passport'),
        ),
    ]
