# Generated by Django 3.1 on 2020-08-17 09:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200817_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirm_code',
            field=models.UUIDField(default=uuid.UUID('5ef90ed1-693b-4661-a471-a345f843aba1'), editable=False),
        ),
    ]
