# Generated by Django 3.1 on 2020-09-05 10:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200905_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='instagram_link',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='vk_link',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='confirm_code',
            field=models.UUIDField(default=uuid.UUID('2cebf7a0-f1c6-48e4-ba5e-058bc98265a5'), editable=False),
        ),
    ]
