# Generated by Django 3.1 on 2020-09-19 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20200905_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='credit_card_number',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
